name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9]+'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck

      - run: /home/runner/.luarocks/bin/luacheck . -q

      - uses: BigWigsMods/packager@master
        with:
          args: -g 1.13.6

      - uses: BigWigsMods/packager@master
